### ISSUE TITLE
lnk plugin issue

### ISSUE THREAD

**Issue by naderhabbbab** [fox-it/dissect.shellitem#15]
Dear Team, 

im getting the following issue when execute  target-query test.tar -f lnk
it extract 28 from 441 lnk the i get the following error

2022-12-23T14:25:22.066848Z [error    ] Unicode link_info_header encountered. Size bigger than 0x00000024. Size encountered:36 [dissect.shellitem.lnk.lnk] 
Traceback (most recent call last):
  File "/usr/local/bin/target-query", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/dissect/target/tools/query.py", line 234, in main
    for record_entries in entry:
  File "/usr/local/lib/python3.10/dist-packages/dissect/target/plugins/os/windows/lnk.py", line 78, in lnk
    lnk_file = Lnk(entry)
  File "/usr/local/lib/python3.10/dist-packages/dissect/shellitem/lnk/lnk.py", line 381, in __init__
    self.linkinfo = LnkInfo(self.fh)
  File "/usr/local/lib/python3.10/dist-packages/dissect/shellitem/lnk/lnk.py", line 202, in __init__
    raise NotImplementedError("Unicode link_info_header parsing not yet implemented")
NotImplementedError: Unicode link_info_header parsing not yet implemented

**Comment by Horofic** [comment]
Will be closing this issue for now. The way the `Unicode link_info_header` error is handled has been changed. This way the plugin still runs, logs the encountered header, and tries to parse the rest of the `lnk` file.

@naderhabbbab if you encounter new issues or find a lnk file which produced this error, feel free to open a new issue!
